runtime: python39

entrypoint: gunicorn -b :$PORT app:app

instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65

# Static files
handlers:
- url: /static
  static_dir: static/
# Let Flask handle all other routes
- url: /.*
  script: auto
